import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "~/styles/Home.module.css";

export default function Home() {
  const time = new Date().toISOString();
  const [browserTime, setBrowserTime] = useState(time);
  useEffect(() => {
    const interval = setInterval(() => {
      setBrowserTime(new Date().toISOString());
    }, 1000);
    return () => clearInterval(interval);
  }, []);
  return (
    <>
      <Head>
        <title>CSR Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="og:image"
          content={`https://${process.env.NEXT_PUBLIC_VERCEL_URL}/api/og?title=CSR`}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <span>
            <p>build time</p>
            <time>{time}</time>
          </span>
          <span>
            <p>browser time</p>
            <time>{browserTime}</time>
          </span>
        </div>
      </main>
    </>
  );
}
